name: Deploy documentation

on:
  repository_dispatch:
    types: [deploy-docs]
    
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build_documentation:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Antora
        run: npm i antora

      - name: Install Antora extensions
        run: |
          npm i @asciidoctor/tabs
          npm i @springio/antora-extensions

      - name: Run Antora
        run: |
          export GIT_CREDENTIALS='https://${{ secrets.PIPELINES_PAT }}@github.com'
          npx antora antora-playbook.yml
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
